web/website/users/models.py
import uuid

from flask import abort, current_app

from flask_admin.contrib.sqla import ModelView
from flask_login import UserMixin, current_user
from itsdangerous import URLSafeTimedSerializer
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.sql import func

from website import db, login_manager, admin


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


class User(UserMixin, db.Model):

    __tablename__ = 'users'

    uuid = db.Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(100), unique=True, nullable=False)
    password = db.Column(db.String(60), nullable=False)
    image_file = db.Column(db.String(20), nullable=False, default='default.jpg')
    registered_on = db.Column(db.DateTime(timezone=True), nullable=False, server_default=func.now())
    confirmed = db.Column(db.Boolean, nullable=False, default=False)
    confirmed_on = db.Column(db.DateTime(timezone=True), nullable=True)
    admin = db.Column(db.Boolean, nullable=False, default=False)

    def __repr__(self):
        return f"User('{self.username}', '{self.email}', '{self.image_file}', '{self.registered_on})"

    def get_id(self):
        return self.uuid

    def generate_token(
        self,
        context='confirm',
        salt_context='confirm-email'
    ):
        serializer = URLSafeTimedSerializer(current_app.config['SECRET_KEY'])
        return serializer.dumps({context: str(self.uuid)}, salt=salt_context)

    def confirm_email_token(
        self,
        token,
        context='confirm',
        salt_context='confirm-email',
        expiration=3600
    ):
        serializer = URLSafeTimedSerializer(current_app.config['SECRET_KEY'])
        try:
            data = serializer.loads(
                token,
                salt=salt_context,
                max_age=expiration
            )
        except:
            return False
        if data.get(context) != str(self.uuid):
            return False
        self.confirmed = True
        self.confirmed_on = func.now()
        return True

    @staticmethod
    def reset_password_token(
        token,
        salt_context='reset-password',
        expiration=3600
    ):
        serializer = URLSafeTimedSerializer(current_app.config['SECRET_KEY'])
        try:
            data = serializer.loads(
                token,
                salt=salt_context,
                max_age=expiration
            )
        except:
            return False
        user = User.query.get(data.get('reset'))
        if user is None:
            return False
        return user
    


class MyModelView(ModelView):
    def is_accessible(self):
        if not current_user.is_anonymous and current_user.admin:
            return current_user.is_authenticated
        return abort(404)
    


admin.add_view(MyModelView(User, db.session))

web/website/users/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileField
from wtforms import (StringField, PasswordField, SubmitField, SelectMultipleField, DateField, TimeField,
                     URLField, TextAreaField, BooleanField)
from wtforms.validators import DataRequired, Length, Email, EqualTo, Regexp, Optional

from ..auth.forms import CustomValidatorsMixin, IntegrityCheck
from ..models import User
from ..utils import PATTERNS


class PasswordChangeForm(CustomValidatorsMixin, FlaskForm):
    old_password = PasswordField('Old password', validators=[DataRequired()])
    new_password = PasswordField('New Password', validators=[DataRequired(), Length(min=8)])
    confirm_password = PasswordField('Confirm New Password',
                                     validators=[DataRequired(), EqualTo('new_password')])
    submit = SubmitField('Update Password')


class EmailChangeForm(CustomValidatorsMixin, FlaskForm):

    email = StringField('New Email',
                        validators=[DataRequired(), Email(), Length(max=100), IntegrityCheck(model=User)])
    old_password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Update Email')


class EntryForm(CustomValidatorsMixin, FlaskForm):

    services = SelectMultipleField('Choose Service', validators=[
                                   DataRequired()
                                   ], id='multiselect', render_kw={"data-placeholder": "Choose service..."},
                                   choices=[], coerce=int)
    date = DateField('Date', validators=[DataRequired()], id='datepicker')
    time = TimeField('Time', validators=[DataRequired()], id='timepicker')
    submit = SubmitField('Create Entry')


class UpdateProfileForm(CustomValidatorsMixin, FlaskForm):
    youtube = URLField('Youtube',
                       validators=[
                           Optional(),
                           Length(max=255),
                           Regexp(PATTERNS['youtube'],
                                  message='Please enter a valid YouTube link'),
                           IntegrityCheck()
                       ],
                       render_kw={"placeholder": "https://www.youtube.com/channel/"})
    website = URLField('Website',
                       validators=[
                           Optional(),
                           Length(max=255),
                           IntegrityCheck()
                       ],
                       render_kw={"placeholder": "https://www.example.com/"})
    vk = URLField('VK',
                  validators=[
                      Optional(),
                      Length(max=255),
                      Regexp(PATTERNS['vk'],
                             message='Please enter a valid VK link'),
                      IntegrityCheck()
                  ],
                  render_kw={"placeholder": "https://vk.com/username"})
    telegram = URLField('Telegram',
                        validators=[
                            Optional(),
                            Length(max=255),
                            Regexp(PATTERNS['telegram'],
                                   message='Please enter a valid Telegram link'),
                            IntegrityCheck()
                        ],
                        render_kw={"placeholder": "https://t.me/username"})
    instagram = URLField('Instagram',
                         validators=[
                             Optional(),
                             Length(max=255),
                             Regexp(PATTERNS['instagram'],
                                    message='Please enter a valid Instagram link'),
                             IntegrityCheck()
                         ],
                         render_kw={"placeholder": "https://instagram.com/username"})
    about = TextAreaField('About', validators=[Optional(), Length(max=255)],
                          render_kw={"placeholder": "Enter information about you"})
    phone_number = StringField('Phone', id='phone', validators=[Optional(), Length(max=50), IntegrityCheck()])
    viber = StringField('Viber', id='viber', validators=[Optional(), Length(max=50), IntegrityCheck()])
    whatsapp = StringField('WhatsApp', id='whatsapp', validators=[Optional(), Length(max=50), IntegrityCheck()])
    first_name = StringField('First Name', validators=[Optional(), Length(max=50)],
                             render_kw={"placeholder": "Enter first name"})
    last_name = StringField('Last Name', validators=[Optional(), Length(max=50)],
                            render_kw={"placeholder": "Enter last name"})
    avatar = FileField('Upload Profile Image', validators=[Optional(), FileAllowed(['jpg', 'png'])])
    delete_avatar = BooleanField('Set profile image to default')
    submit = SubmitField('Update Profile')

web/website/users/routes.py
from urllib.parse import urlparse, ParseResult
from uuid import UUID

from flask import flash, render_template, redirect, url_for, session, Blueprint, request, current_app, abort
from flask_login import login_required
import phonenumbers
import sqlalchemy as sa
from sqlalchemy.sql import func
from werkzeug.wrappers.response import Response

from .forms import PasswordChangeForm, EmailChangeForm, EntryForm, UpdateProfileForm
from .. import db
from ..api.common import can_create_entry
from ..models import User, Entry, Service, current_user, get_or_404
from ..utils import send_email, email_confirmed, current_user_required, save_image, delete_image

users = Blueprint('users', __name__)


@users.route("/<username>/profile", methods=['GET'])
@login_required
@email_confirmed
def profile(username: str) -> Response | str:
    user = db.session.scalar(sa.select(User).filter_by(username=username)) or abort(404)
    prev_entry = db.session.scalar(
        user.entries.select()
        .filter(sa.or_(
            Entry.date < func.current_date(), sa.and_(
                Entry.date == func.current_date(),
                Entry.time <= func.current_time())))
        .order_by(Entry.date.desc(), Entry.time.desc()))
    next_entry = db.session.scalar(
        user.entries.select()
        .filter(sa.or_(
            Entry.date > func.current_date(), sa.and_(
                Entry.date == func.current_date(),
                Entry.time > func.current_time())))
        .order_by(Entry.date, Entry.time))
    form: dict[str, str | None] = {}
    for item in ['phone_number', 'viber', 'whatsapp']:
        try:
            p = phonenumbers.parse(getattr(user.socials, item))
        except phonenumbers.phonenumberutil.NumberParseException:
            form[item] = None
            continue
        formatted_number = phonenumbers.format_number(p, phonenumbers.PhoneNumberFormat.INTERNATIONAL)
        form[item] = formatted_number
    for item in ['vk', 'telegram', 'instagram']:
        form[item] = None
        url = getattr(user.socials, item)
        if url:
            parsed: ParseResult = urlparse(url=url)
            form[item] = parsed.path.strip('/')
    return render_template('users/profile.html',
                           title='Profile',
                           user=user,
                           form=form,
                           prev_entry=prev_entry,
                           next_entry=next_entry)


@users.route("/<username>/profile/change-password", methods=['GET', 'POST'])
@login_required
@email_confirmed
@current_user_required
def change_password_request(username: str) -> Response | str:
    form = PasswordChangeForm()
    if form.validate_on_submit():
        current_user.password = form.new_password.data
        db.session.add(current_user)
        db.session.commit()
        flash('Your password has been updated.', 'success')
        return redirect(url_for('users.profile', username=username))
    return render_template('users/change_password.html',
                           title='Change Password',
                           legend='Change Password', form=form)


@users.route("/<username>/profile/change-email", methods=['GET', 'POST'])
@login_required
@email_confirmed
@current_user_required
def change_email_request(username: str) -> Response | str:
    form = EmailChangeForm()
    if form.validate_on_submit():
        session['new_email'] = form.email.data.lower()
        token = current_user.generate_token(context='change', salt_context='change-email')
        change_url = url_for('users.change_email', username=username, token=token, _external=True)
        template = 'users/email/change_email'
        subject = "Please confirm your email"
        send_email(form.email.data, subject, template, change_url=change_url, user=current_user)
        flash('An email with instructions to confirm your new email address has been sent.', 'info')
        return redirect(url_for('users.profile', username=username))
    return render_template('users/change_email.html', title='Change Email', legend='Change Email', form=form)


@users.route("/<username>/profile/change-email/<token>", methods=['GET', 'POST'])
@login_required
@email_confirmed
@current_user_required
def change_email(username: str, token: str | bytes) -> Response:
    if current_user.confirm_email_token(token, context='change', salt_context='change-email'):
        new_email = session.get('new_email')
        if new_email is not None:
            current_user.email = new_email
            db.session.add(current_user)
            db.session.commit()
            flash('Your email address has been updated.', 'success')
            return redirect(url_for('users.profile', username=username))
        else:
            flash('Something went wrong. Please try again.', 'danger')
            return redirect(url_for('users.change_email_request', username=username))
    else:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.change_email_request', username=username))


@users.route("/<username>/profile/create-entry", methods=['GET', 'POST'])
@login_required
@email_confirmed
@current_user_required
def create_entry(username: str) -> Response | str:
    user = db.session.scalar(sa.select(User).filter_by(username=username)) or abort(404)
    services = db.session.scalars(sa.select(Service)).all()
    form = EntryForm()
    form.services.choices = [(service.id, service.name) for service in services]
    if form.validate_on_submit():
        service_types = [
            db.session.execute(sa.select(Service).filter_by(id=service_id)).scalar_one()
            for service_id in form.services.data
        ]
        entry = Entry(date=form.date.data,
                      time=form.time.data,
                      user_id=current_user.uuid)
        entry.services.extend(service_types)
        available = can_create_entry(entry)
        if available:
            db.session.add(entry)
            db.session.commit()
            flash('New entry has been created.', 'success')
            return redirect(url_for('users.my_entries', username=username))
        else:
            flash('Please choose different date or time', 'danger')
    return render_template('users/create_entry.html', title='Profile', form=form, user=user)


@users.route("/<username>/profile/edit-entry/<uuid:entry_id>", methods=['GET', 'POST'])
@login_required
@email_confirmed
@current_user_required
def edit_entry(username: str, entry_id: UUID) -> Response | str:
    entry = get_or_404(Entry, entry_id)
    if entry.user.username != username:
        abort(404)
    user = db.session.scalar(sa.select(User).filter_by(username=username)) or abort(404)
    services = db.session.scalars(sa.select(Service)).all()
    form = EntryForm()
    form.services.choices = [(service.id, service.name) for service in services]
    if form.validate_on_submit():
        service_types = [
            db.session.execute(sa.select(Service).filter_by(id=service_id)).scalar_one()
            for service_id in form.services.data
        ]
        entry.date = form.date.data
        entry.time = form.time.data
        entry.services.clear()
        entry.services.extend(service_types)
        available = can_create_entry(entry, context='update')
        if available:
            db.session.commit()
            flash('Your entry has been updated.', 'success')
            return redirect(url_for('users.my_entries', username=username))
        else:
            flash('Please choose different date or time', 'danger')
    return render_template('users/edit_entry.html', title='Profile', form=form, user=user)


@users.route("/<username>/profile/cancel-entry/<uuid:entry_id>", methods=['GET', 'POST'])
@login_required
@email_confirmed
@current_user_required
def cancel_entry(username: str, entry_id: UUID) -> Response:
    entry = get_or_404(Entry, entry_id)
    if entry.user.username != username:
        abort(404)
    db.session.delete(entry)
    db.session.commit()
    flash('Your entry has been cancelled!', 'info')
    return redirect(url_for('users.my_entries', username=username))


@users.route("/<username>/profile/my-entries", methods=['GET', 'POST'])
@login_required
@email_confirmed
@current_user_required
def my_entries(username: str) -> str:
    entries = db.session.scalars(current_user.entries
                                 .select()
                                 .order_by(Entry.date.desc(), Entry.time.desc())).all()
    return render_template('users/my_entries.html', title='Profile', entries=entries)


@users.route("/<username>/profile/update", methods=['GET', 'POST'])
@login_required
@email_confirmed
@current_user_required
def update_profile(username: str) -> Response | str:
    user = db.session.scalar(sa.select(User).filter_by(username=username)) or abort(404)
    form = UpdateProfileForm()
    if form.validate_on_submit():
        for field in form._fields.values():
            if field.name not in ['delete_avatar', 'submit', 'csrf_token']:
                if field.data and field.name in ['instagram', 'telegram', 'vk']:
                    field.data = field.data.lower()
                elif field.data and field.name in ['first_name', 'last_name']:
                    field.data = field.data.capitalize()
                elif form.delete_avatar.data and field.name in ['avatar']:
                    delete_image(user.socials.avatar, path='profiles')
                    field.data = current_app.config['DEFAULT_AVATAR']
                elif field.data and field.name in ['avatar']:
                    delete_image(user.socials.avatar, path='profiles')
                    field.data = save_image(form.avatar.data, path='profiles')
                elif field.name in ['avatar']:
                    field.data = user.socials.avatar
                elif not field.data:
                    field.data = None
                setattr(user.socials, field.name, field.data)

web/website/templates/users/change_email.html
{% extends "layout.html" %}
{% from "_form_macro.html" import render_icon_field %}
{% block content %}
<div class="content-section">
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            {{render_icon_field(form.email, "fa-solid fa-envelope fa-xl text-light", "bg-primary")}}
            {{render_icon_field(form.old_password, "fa-solid fa-key fa-xl text-light", "bg-primary")}}
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

web/website/templates/users/change_password.html
{% extends "layout.html" %}
{% from "_form_macro.html" import render_icon_field %}
{% block content %}
<div class="content-section">
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            {{render_icon_field(form.old_password, "fa-solid fa-key fa-xl text-light", "bg-primary")}}
            {{render_icon_field(form.new_password, "fa-solid fa-key fa-xl text-light", "bg-primary")}}
            {{render_icon_field(form.confirm_password, "fa-solid fa-key fa-xl text-light", "bg-primary")}}
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

web/website/templates/users/my_entries.html
{% extends "layout.html" %}
{% block content %}
{% for entry in entries %}
<ul>
    <li>{{entry.uuid}}</li>
    <ul>
        {% for service in entry.services %}

        <li>{{service.name}}{{service.duration}}</li>
        {%endfor%}
    </ul>
    <li>{{entry.created_on}}</li>
    <li>{{entry.date}}</li>
    <li>{{entry.time}}</li>
    <li>{{entry.user_id}}</li>
</ul>
<a class="btn btn-outline-primary ms-1"
    href="{{url_for('users.edit_entry', username=current_user.username, entry_id=entry.uuid)}}" role="button">Edit
    Entry</a>
<a href="{{ url_for('users.cancel_entry', username=current_user.username, entry_id=entry.uuid)}}"
    class="btn btn-outline-danger" role="button">Cancel
    Entry</a>
{% endfor %}



{% endblock content %}

web/website/templates/users/profile.html
{% extends "layout.html" %}
{% block content %}
<section style="background-color: #eee;">

    <div class="row">
        <div class="col-lg-4">
            <div class="card mb-4">
                <div class="card-body text-center">
                    <div class="thumbnail profile-avatar">
                        <img class="account-img"
                            src="{{ url_for('static', filename='images/profiles/' + user.socials.avatar) }}"
                            alt="avatar">
                    </div>
                    <h5 class="my-3">{{ user.username }}</h5>
                    <p class="text-muted mb-1">Full Stack Developer</p>
                    <p class="text-muted mb-4">Bay Area, San Francisco, CA</p>
                    <div class="d-flex justify-content-center mb-2">
                        <!-- <button type="button" class="btn btn-primary">Follow</button> -->
                        <!-- <button type="button" class="btn btn-outline-primary ms-1">Message</button> -->
                        <a class="btn btn-primary"
                            href="{{url_for('users.create_entry', username=current_user.username)}}"
                            role="button">Create Entry</a>
                        <a class="btn btn-outline-primary ms-1"
                            href="{{url_for('users.my_entries', username=current_user.username)}}" role="button">My
                            Entries</a>

                    </div>
                </div>
            </div>
            <div class="card mb-4 mb-lg-0">
                <div class="card-body p-0">
                    <ul class="list-group list-group-flush rounded-3">
                        <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                            <div>
                                <i class="fa-brands fa-youtube fa-xl text-danger"></i>
                                <p>YouTube</p>
                            </div>
                            <p class="mb-0">{%if user.socials.youtube%}<a href="{{user.socials.youtube}}"
                                    target="_blank">Youtube</a>{%else%}&nbsp;{%endif%}</p>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                            <div>
                                <i class="fab fa-vk fa-xl text-primary"></i>
                                <p>VK</p>
                            </div>
                            <p class="mb-0">{%if form.vk%}<a href="{{user.socials.vk}}"
                                    target="_blank">{{form.vk}}</a>{%else%}&nbsp;{%endif%}</p>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                            <div>
                                <i class="fa-brands fa-telegram fa-xl text-primary"></i>
                                <p>Telegram</p>
                            </div>
                            <p class="mb-0">{%if form.telegram%}<a href="{{user.socials.telegram}}"
                                    target="_blank">@{{form.telegram}}</a>{%else%}&nbsp;{%endif%}</p>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                            <div>
                                <i class="fa-brands fa-instagram fa-xl text-warning"></i>
                                <p>Instagram</p>
                            </div>
                            <p class="mb-0">{%if form.instagram%}<a href="{{user.socials.instagram}}"
                                    target="_blank">@{{form.instagram}}</a>{%else%}&nbsp;{%endif%}</p>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                            <div>
                                <i class="fas fa-globe fa-xl text-warning"></i>
                                <p>Website</p>
                            </div>
                            <p class="mb-0">{%if user.socials.website%}<a href="{{user.socials.website}}"
                                    target="_blank">Website</a>{%else%}&nbsp;{%endif%}</p>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-lg-8">
            <div class="card mb-4">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-3">
                            <i class="fas fa-id-card fa-xl text-primary"></i>
                            <p class="mb-0">Full Name</p>
                        </div>
                        <div class="col-sm-9">
                            <p class="text-muted mb-0">{%if
                                user.socials.first_name%}{{user.socials.first_name}}{%endif%}
                                {%if user.socials.last_name%}{{user.socials.last_name}}{%endif%}</p>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <i class="fa-solid fa-envelope fa-xl text-primary"></i>
                            <p class="mb-0">Email</p>
                        </div>
                        <div class="col-sm-9">
                            <p class="text-muted mb-0">{{user.email}}</p>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <i class="fa-solid fa-phone fa-xl text-primary"></i>
                            <p class="mb-0">Mobile</p>
                        </div>
                        <div class="col-sm-9">
                            <p class="text-muted mb-0">{% if form.phone_number%}{{form.phone_number}}{%endif%}</p>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <i class="fa-brands fa-viber fa-xl text-primary"></i>
                            <p class="mb-0">Viber</p>
                        </div>
                        <div class="col-sm-9">
                            <p class="text-muted mb-0">{% if form.viber%}{{form.viber}}{%endif%}</p>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <i class="fa-brands fa-whatsapp fa-xl text-primary"></i>
                            <p class="mb-0">WhatsApp</p>
                        </div>
                        <div class="col-sm-9">
                            <p class="text-muted mb-0">{% if form.whatsapp%}{{form.whatsapp}}{%endif%}</p>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <i class="fa-solid fa-circle-info fa-xl text-primary"></i>
                            <p class="mb-0">About</p>
                        </div>
                        <div class="col-sm-9">
                            <p class="text-muted mb-0">{% if form.about%}{{user.socials.about}}{%endif%}</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="card mb-4 mb-md-0">
                        <div class="card-body">
                            <p class="mb-4"><span class="text-primary font-italic me-1">Previous</span> Entry</p>
                            <p class="mb-1" style="font-size: .77rem;">Web Design</p>
                            <div style="min-height: 200px;">
                                {% if prev_entry %}
                                <div style="width: 80%">
                                    <p>Your previous entry was on {{prev_entry.date.strftime('%d %B %Y,
                                        %A')}}{{prev_entry.time.strftime(' %H:%M')}}</p>
                                    <ul>
                                        {% for service in prev_entry.services %}
                                        <li>{{service}}</li>
                                        {% endfor %}
                                    </ul>
                                </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card mb-4 mb-md-0">
                        <div class="card-body">
                            <p class="mb-4"><span class="text-primary font-italic me-1">Next</span> Entry</p>
                            <p class="mb-1" style="font-size: .77rem;">Web Design</p>
                            <div style="min-height: 200px;">
                                {% if next_entry %}
                                <div style="width: 80%">
                                    <p>Your next entry will be on {{next_entry.date.strftime('%d %B %Y,
                                        %A')}}{{next_entry.time.strftime(' %H:%M')}}</p>
                                    <ul>
                                        {% for service in next_entry.services %}
                                        <li>{{service}}</li>
                                        {% endfor %}
                                    </ul>
                                </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</section>
{% endblock%}
{%block sidebar_list %}


<li class="list-group-item list-group-item-light"><a class="btn btn-outline-success ms-1"
        href="{{url_for('users.update_profile', username=current_user.username)}}" role="button">Update Profile</a></li>
<li class="list-group-item list-group-item-light"><a class="btn btn-outline-success ms-1"
        href="{{ url_for('users.change_password_request', username=current_user.username) }}" role="button">Change
        Password</a></li>
<li class="list-group-item list-group-item-light"><a class="btn btn-outline-success ms-1"
        href="{{ url_for('users.change_email_request', username=current_user.username) }}" role="button">Change
        Email</a></li>
{% endblock %}