web/website/main/routes.py
from flask import render_template, Blueprint, flash, redirect, url_for, abort, request, jsonify
import sqlalchemy as sa
from sqlalchemy.sql import text
from werkzeug.exceptions import HTTPException
from werkzeug.wrappers.response import Response

from .. import db
from .forms import PostForm, EditPostForm
from .. models import Post, current_user
from .. utils import admin_required, save_image, delete_image

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home() -> str:
    posts = db.session.scalars(sa.select(Post).order_by(Post.posted_on.desc()))
    return render_template('home.html', title='Home', posts=posts)


@main.route("/about")
def about() -> str:
    return render_template('about.html', title='About')


def handle_error(error: HTTPException) -> Response | tuple[str, int]:
    if (request.mimetype or request.headers['accept']) == 'application/json':
        response = jsonify({
            'code': error.code,
            'message': error.name,
            'description': error.description,
        })
        response.status_code = error.code  # type: ignore[assignment]
        response.content_type = 'application/json'
        return response
    return render_template(f'{error.code}.html', title='Page Not Found'), error.code  # type: ignore[return-value]


@main.route("/create-post", methods=['GET', 'POST'])
@admin_required
def create_post() -> Response | str:
    form = PostForm()
    if form.validate_on_submit():
        image = save_image(form.image.data) if form.image.data else None
        post = Post(title=form.title.data, image=image, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='Create Post', legend='Create Post', form=form)


@main.route("/edit-post/<int:post_id>", methods=['GET', 'POST'])
@admin_required
def edit_post(post_id: int) -> Response | str:
    form = EditPostForm()
    post = db.session.get(Post, post_id) or abort(404)
    if form.validate_on_submit():
        if form.delete_image.data:
            image = None
            delete_image(post.image)
        elif form.image.data:
            image = save_image(form.image.data)
            delete_image(post.image)
        else:
            image = post.image
        post.title = form.title.data
        post.image = image  # type: ignore[assignment]
        post.content = form.content.data
        db.session.add(post)
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('main.home'))
    form.title.data = post.title
    form.content.data = post.content
    return render_template('edit_post.html', title='Edit Post', legend='Edit Post', form=form)


@main.route("/delete-post/<int:post_id>", methods=['GET', 'POST'])
@admin_required
def delete_post(post_id: int) -> Response:
    post = db.session.get(Post, post_id) or abort(404)
    delete_image(post.image)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))


@main.route('/up')
@admin_required
def up() -> str:
    db.session.execute(text('SELECT 1'))
    return 'Healthy: OK'

web/website/templates/405.html
{% extends 'layout.html' %}
{% block content %}405 Method Not Allowed{% endblock %}

web/website/templates/_form_macro.html
{% macro render_icon_field(field, icon_class, bg_color="bg-white") %}
<div class="form-group">
    {{ field.label(class="form-control-label") }}
    {% if field.errors %}
    <div class="input-group">
        <span class="input-group-text {{ bg_color }}"><i class="{{ icon_class }}"></i></span>
        {{ field(class="form-control is-invalid") }}
        <div class="invalid-feedback">
            <ul>
                {% for error in field.errors %}
                <li><span>{{ error }}</span></li>
                {% endfor %}
            </ul>
        </div>
    </div>
    {% else %}
    <div class="input-group">
        <span class="input-group-text {{ bg_color }}"><i class="{{ icon_class }}"></i></span>
        {{ field(class="form-control") }}
    </div>
    {% endif %}
</div>

{% endmacro %}

{% macro render_field(field) %}
<div class="form-group">
    {{ field.label(class="form-control-label") }}
    {% if field.errors %}
    <div class="input-group">
        {{ field(class="form-control is-invalid") }}
        <div class="invalid-feedback">
            <ul>
                {% for error in field.errors %}
                <li><span>{{ error }}</span></li>
                {% endfor %}
            </ul>
        </div>
    </div>
    {% else %}
    <div class="input-group">
        {{ field(class="form-control") }}
    </div>
    {% endif %}
</div>

{% endmacro %}

web/website/templates/about.html
{% extends 'layout.html' %}

web/website/templates/activate.html
<p>Welcome! Thanks for signing up. Please follow this link to activate your account:</p>
<p><a href="{{ confirm_url }}">{{ confirm_url }}</a></p>
<br>
<p>Cheers!</p>

web/website/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                {{ form.title(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.title.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>

            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                {{ form.content(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.content.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.image.label(class="form-control-label") }}
                {% if form.image.errors %}
                {{ form.image(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.image.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.image(class="form-control form-control-lg") }}
                {% endif %}
            </div>

        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
    {{ ckeditor.load() }}
    {{ ckeditor.config(name='body') }}
</div>
{% endblock content %}

web/website/templates/edit_post.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                {{ form.title(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.title.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>

            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                {{ form.content(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.content.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.image.label(class="form-control-label") }}
                {% if form.image.errors %}
                {{ form.image(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.image.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.image(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-check">
                {{ form.delete_image(class="form-check-input") }}
                {{ form.delete_image.label(class="form-check-label") }}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
    {{ ckeditor.load() }}
    {{ ckeditor.config(name='body') }}
</div>
{% endblock content %}

web/website/templates/home.html
{% extends 'layout.html' %}
{% block content %}


{% for post in posts %}
<article class="media content-section">

    <div class="media-body">

        <div class="article-metadata">
            <div class="article-metadata-avatar">
                <div class="thumbnail author-avatar">
                    <img class="account-img "
                        src="{{ url_for('static', filename='images/profiles/' + post.author.socials.avatar) }}">
                </div>
            </div>
            <div class="article-metadata-author">
                <a href="{{url_for('users.profile', username=post.author.username)}}">{{post.author.username }}</a>
            </div>
            <div class="article-metadata-date">
                <small class="text-muted">{{ post.posted_on.strftime('%Y-%m-%d %H:%M') }}</small>
            </div>
            {% if current_user.admin%}
            <a href="{{ url_for('main.edit_post', post_id=post.id)}}"><i
                    class="fas fa-edit fa-lg text-success ms-2"></i></a>
            <a href="{{ url_for('main.delete_post', post_id=post.id)}}"><i
                    class="fa-solid fa-trash-can fa-lg text-danger ms-2"></i></a>
            {% endif %}
        </div>

        <div class="card article-content">
            <div class="article-title">
                <h4 class="card-title"><a class="article-link" href="{{ url_for('main.home', post=post.id) }}">{{
                        post.title }}</a></h4>

            </div>
            {% if post.image %}
            <div class="article-image">
                <img src="{{url_for('static', filename='images/posts/' + post.image)}} " alt="" srcset="">
            </div>
            {% endif %}
            <div class="article-text">
                <p>{{ post.content | safe }}</p>
            </div>
        </div>
    </div>
</article>
{% endfor %}

{% endblock %}
{%block sidebar_list %}
{% if current_user.admin%}
<a href="{{ url_for('main.create_post')}}" class="btn btn-outline-success" role="button">Create New Post</a>
{% endif %}

{% endblock %}

web/website/templates/layout.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
        integrity="sha256-wLz3iY/cO4e6vKZ4zRmo4+9XDpMcgKOvv/zEU3OMlRo=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
        integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" type="text/css" href="https://npmcdn.com/flatpickr/dist/themes/airbnb.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" />
    <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/select2-bootstrap-5-theme@1.3.0/dist/select2-bootstrap-5-theme.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.21/css/intlTelInput.css"
        integrity="sha512-gxWow8Mo6q6pLa1XH/CcH8JyiSDEtiwJV78E+D+QP0EVasFs8wKXq16G8CLD4CJ2SnonHr4Lm/yY2fSI2+cbmw=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />


    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    {% block scripts %}
    <script defer src="https://cdn.jsdelivr.net/npm/jquery@3.5.0/dist/jquery.slim.min.js"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
        integrity="sha256-m81NDyncZVbr7v9E6qCWXwx/cwjuWDlHCMzi9pjMobA=" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.21/js/intlTelInput.min.js"
        integrity="sha512-x1RjK1QHIg0CA4lP7CFG98UXDy04pYBPuepiMd4bkJ7sqEfAPHNmVbkBxVDG3zpnolqMX2cd1mX13HlvwZfA8w=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script defer src="{{ url_for('static', filename='js/main.js') }}"></script>
    {% endblock %}

    {% if title %}
    <title>Juliya Nails - {{ title }}</title>
    {% else %}
    <title>Juliya Nails</title>
    {% endif %}

</head>

<body>
    <header class="site-header mb-4">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Juliya Nails</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link active" aria-current="page" href="{{url_for('main.home')}}">Home</a>
                        <a class="nav-link" href="{{url_for('main.about')}}">About</a>
                        <a class="nav-link" href="/api/docs">API</a>

                    </div>
                    <div class="navbar-nav ms-auto">
                        {% if current_user.is_authenticated %}
                        {% if current_user.admin %}
                        <a class="nav-item nav-link" href="{{ url_for('admin.index') }}">Admin Panel</a>
                        {% endif %}
                        {% if current_user.confirmed and current_user.is_authenticated %}
                        <a class="nav-item nav-link"
                            href="{{ url_for('users.profile', username=current_user.username)}}">Profile</a>
                        {% else %}
                        <a class="nav-item nav-link" href="{{ url_for('auth.unconfirmed') }}">Confirm</a>
                        {% endif %}
                        <a class="nav-item nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                        {% else %}
                        <a class="nav-item nav-link" href="{{ url_for('auth.login') }}">Login</a>
                        <a class="nav-item nav-link" href="{{ url_for('auth.register') }}">Register</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}
                {% endwith %}
            </div>
        </div>
        {% block main %}

        <div class="row">
            <div class="col-md-10">
                {% block content %}{% endblock %}
            </div>
            {%block sidebar %}
            <div class="col-md-2">
                <div class="content-section">
                    <h3>Our Sidebar</h3>
                    <p class='text-muted'>You can put any information here you'd like.
                    <ul class="list-group">
                        <!-- <li class="list-group-item list-group-item-light">Latest Posts</li>
                        <li class="list-group-item list-group-item-light">Announcements</li>
                        <li class="list-group-item list-group-item-light">Calendars</li>
                        <li class="list-group-item list-group-item-light">etc</li> -->
                        {%block sidebar_list %}
                        {% endblock %}
                    </ul>
                    </p>
                </div>
            </div>
            {% endblock %}
        </div>
        {% endblock %}

    </main>







</body>

</html>

web/website/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Log In</legend>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-check">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
            <small class="text-muted ml-2">
                <a href="{{ url_for('users.password_reset_request') }}">Forgot Password?</a>
            </small>
        </div>
    </form>
</div>
<div class="border-top pt-3">
    <small class="text-muted">
        Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
    </small>
</div>
{% endblock content %}

web/website/templates/register.html
{% extends 'layout.html' %}

{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Join Today</legend>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}

                {% if form.username.errors %}
                {{ form.username(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                {% if form.confirm_password.errors %}
                {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.confirm_password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.confirm_password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
<div class="border-top pt-3">
    <small class="text-muted">
        Already Have An Account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
    </small>
</div>
{% endblock content %}

web/website/templates/reset.html
<p>To reset your password, visit the following link:</p>
<p><a href="{{ reset_url }}">{{ reset_url }}</a></p>
<br>
<p>If you didn't make a request, simply ignore this message.</p>

web/website/templates/unconfirmed.html
{% extends 'layout.html' %}

{% block content %}

<h1>Welcome!</h1>
<br>
<p>You have not confirmed your account. Please check your inbox (and your spam folder) - you should have received an
    email with a confirmation link.</p>
<p>Didn't get the email? <a href="{{ url_for('users.resend_confirmation') }}">Resend</a>.</p>

{% endblock %}